[build]
builder = "nixpacks"
buildCommand = "npm run install-all && npm run build"

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3 